[package]
version = "0.1.4"
edition = "2018"
name = "tracing-layer-slack-examples"
description = "Example implementation for Slack"
publish = false

[dependencies]
tracing-layer-slack = { path = "../../layers/slack" }

tokio = { version = "1", default-features = false, features = ["test-util", "sync", "macros", "rt-multi-thread"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3"
regex = "1"
