[package]
name = "tracing-layer-discord"
version = "0.4.1"
edition = "2018"
license = "Apache-2.0"
description = "Send filtered tracing events to Discord"
documentation = "https://docs.rs/tracing-layer-discord"
repository = "https://github.com/seanpianka/tracing-layer-slack-discord/"
readme = "README.md"
keywords = ["tracing", "layer", "discord", "async", "filter"]
categories = ["development-tools::debugging", "asynchronous"]

[lib]
name = "tracing_layer_discord"
path = "src/lib.rs"
doctest = false

[features]
default = ["rustls", "gzip", "log-errors"]
gzip = [ "tracing-layer-core/gzip" ]
native-tls = [ "tracing-layer-core/native-tls" ]
rustls = [ "tracing-layer-core/rustls" ]
log-errors = [ "tracing-layer-core/log-errors" ]

[dependencies]
tracing-layer-core = { path = "../../core", version = "0.4.1"}

regex = "1"
serde_json = "1.0"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["registry"] }

[dev-dependencies]
tokio = { version = "1", features = ["io-util", "macros", "net", "rt-multi-thread"] }
tracing-bunyan-formatter = { default-features = false, version = "0.3" }
